Trees - Binary Tree Mirror
dansmyers/InterviewQuestionGuide pull request #12
Opened 2020-04-02 06:38 UTC by mariellaPariente

2020-04-05 12:57 UTC, dansmyers requested changes
Hi, Mariella. The content looks good. I like the images. There's one thing I think you should clarify before accepting the request.

The intro section talks about mirroring and inverting as if they're the same problem. I believe that inverting usually refers to a problem where the you reverse the parent-child relationships. It's a similar problem, but not the same as mirroring. You can rewrite the first section to make it clear that mirroring is an example of a general class of tree-manipulation problems, which also includes inverting parent-child relationships.

Also, make a subfolder to hold your images and update your links to load the images out of the subfolder, so that the top-level Tree directory contains only the main .md files describing the problems.

2020-04-05 23:47 UTC, mariellaPariente commented
Hi Dr. Myers, 
I made the requested changes and added a /treeImages folder. Regarding the .md file correction, there were several sources I looked at online, that used "mirroring" and "inverting" interchangeably so it was confusing to me as well. I think it's better now, let me know if it is still not clear.

2020-04-05 23:52 UTC, mariellaPariente commented
Hi Dr. Myers,

I just sent a pull request with the corrections. Not sure if I did it right, let me know.

-Mariella
________________________________
From: Dan S. Myers <notifications@github.com>
Sent: Sunday, April 5, 2020 5:57 AM
To: dansmyers/InterviewQuestionGuide <InterviewQuestionGuide@noreply.github.com>
Cc: Mariella Pariente <MPARIENTE@Rollins.edu>; Author <author@noreply.github.com>
Subject: Re: [dansmyers/InterviewQuestionGuide] Trees - Binary Tree Mirror (#12)


* External Email *


@dansmyers requested changes on this pull request.

Hi, Mariella. The content looks good. I like the images. There's one thing I think you should clarify before accepting the request.

The intro section talks about mirroring and inverting as if they're the same problem. I believe that inverting usually refers to a problem where the you reverse the parent-child relationships. It's a similar problem, but not the same as mirroring. You can rewrite the first section to make it clear that mirroring is an example of a general class of tree-manipulation problems, which also includes inverting parent-child relationships.

Also, make a subfolder to hold your images and update your links to load the images out of the subfolder, so that the top-level Tree directory contains only the main .md files describing the problems.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/dansmyers/InterviewQuestionGuide/pull/12#pullrequestreview-387816260>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AKHWPWRBY4OJ7MIF5QAL5VLRLB53NANCNFSM4L2A64JQ>.

2020-04-07 17:59 UTC, dansmyers approved these changes

2020-04-07 17:59 UTC, merged